AWSTemplateFormatVersion: '2010-09-09'
Description: RDS Template

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
  DBInstanceClass:
    Type: String
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "^[a-zA-Z0-9!@#$%^&*()_+=\\[\\]{}|;:,.<>?~-]+$"
    ConstraintDescription: >-
      Password must be 8–41 characters and may include letters, numbers, and these special characters:
      ! @ # $ % ^ & * ( ) _ + = [ ] { } | ; : , . < > ? ~ -

  DBName:
    Type: String
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9_]{0,63}$"
    ConstraintDescription: >
      DBName must start with a letter and contain only alphanumeric characters or underscores (no special characters).


Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for RDS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      EngineVersion: 8.0.40
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      BackupRetentionPeriod: 7
      DeletionProtection: false

Outputs:
  DatabaseEndpoint:
    Description: Endpoint of the RDS instance
    Value: !GetAtt Database.Endpoint.Address
